### ISSUE TITLE
janus binary is missing

### ISSUE THREAD

**Issue by JuniorJPDJ** [lz00qs/orangepi-zero3-pikvm-builder#3]
This blocks webRTC from usage.

PS. Very cool image, nice to have very cheap kvm :D

**Comment by lz00qs** [comment]
> This blocks webRTC from usage.
> 
> PS. Very cool image, nice to have very cheap kvm :D

Sorry for the late reply, could you please send me more information about this issue?

**Comment by JuniorJPDJ** [comment]
When you enable webrtc (described in official docs) there's error about missing janus binary.

**Comment by lz00qs** [comment]
> When you enable webrtc (described in official docs) there's error about missing janus binary.

This device does not support webrtc because it uses a usb video capture card, which is described in the official pikvm documentation (https://docs.pikvm.org/webrtc/). Thanks for your feedback, I'll note this issue in the readme later (https://github.com/lz00qs/orangepi-zero3-pikvm).
